version: '3.8'

services:
  redis:
    image: redis:7
    container_name: ${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
